---
image: alpine:3.15

Test:
    stage: test
    before_script:
        - apk add -q bash curl openjdk11
        - curl -O https://download.clojure.org/install/linux-install-1.11.1.1105.sh
        - chmod +x linux-install-1.11.1.1105.sh
        - ./linux-install-1.11.1.1105.sh
    script:
        - clojure -X:test/cloverage
    coverage: '/.*ALL FILES\s+\|\s+(\d+.\d+)\s+\|.*$/'
